### PR TITLE
Update migrate.rst

### PR DESCRIPTION
**Pull request by frossie**
Updates for a more guided linear flow

### CODE REVIEW

**Comment by frossie** [comment]
PS> I have not been able to preview this because https://documenteer.lsst.io/v/index.html is not showing my branch so sorry for any layout issues

**Comment by jonathansick** [comment]
Thanks. I'll fix up this PR next week.

**Comment by jonathansick** [comment]
(The GitHub Actions workflow is set up to only publish preview for ticket branches)

**Comment by frossie** [comment]
You're meant to be on vacation, go away. I fixed the formatting issues by RTFMing and tox -e docs.

**Comment by jonathansick** [comment]
Ah, I understand the intent of the changes. The doc was originally written for a manual migration, and then the automated tool was shoehorned in when it became available. The flow of the migration here was better, but I went further and oriented the steps around setting up and running the manual migration, and then I turned the original manual migration section into a reference. It should read a lot more simply now. Thanks.

**Pull request merged**
