### PR TITLE
DM-11415: Additional roles for creating ls.st links to DocuShare handles

### PR DESCRIPTION
**Pull request by jonathansick**
Support for

- LTS
- LEP
- LCA
- LSSTC
- LCR
- LCN
- DMTR
- SPT
- Document (displays in title case, Document-1)
- Report (displays in title case)
- Minutes (displays in title case)
- Collection (displays in title case)
- SQR
- DMTN
- SMTN

### CODE REVIEW

**Comment by timj** [comment]
Don't forget SPT...

**Comment by timj** [comment]
If this bypasses the use of references I'm not sure I'm happy with it. If we encourage people to say
```
:ldm:503
```
then people won't be doing
```
:cite:`LDM-503`
```
and the references will become half-baked. Can the role add a `:cite:` implicitly?

**Comment by jonathansick** [comment]
@timj What does SPT stand for?

**Comment by timj** [comment]
Support document (see LPM-51). This is relevant because an SPT document was part of the DM review this week.

**Comment by timj** [comment]
SPT-432 is the relevant example.

**Comment by jonathansick** [comment]
Hm, https://ls.st/spt-432 points to https://jira.lsstcorp.org/browse/SPT-432. Is this a known bug with `ls.st`?

**Comment by timj** [comment]
https://jira.lsstcorp.org/browse/IHS-384

**Pull request merged**
